spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webchat
    username: postgres
    password: 4747
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
#spring:
#  datasource:
#    #    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:~/testdb
#    driver-class-name: org.h2.Driver
#    username: sam
#    password: 4747
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true